# Basic set up for three package managers
version: 2
updates:
  # Maintain dependencies for Composer
  - package-ecosystem: "gomod"
    directory: "./"
    reviewers:
      - "Matrix278"
      - "KostLinux"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: '[Go Modules]'
      include: scope