name: Verify Code
run-name: Verify code changes
on:
  pull_request:
    types:
        - opened
        - synchronize
        - edited
        - closed

env:
  GOPROXY: https://proxy.golang.org

permissions:
    contents: read
    packages: read
    statuses: write
    pull-requests: write

jobs:             
    verify_backend_quality:
      name: Verify Backend Code Quality
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v4
          with:
            version: v1.56.2
            working-directory: ./
            only-new-issues: false
            args: --concurrency=16 --timeout=5m --out-format=github-actions --issues-exit-code=1
            skip-cache: false
            skip-pkg-cache: true