name: Verify & Release
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - closed
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GOPROXY: https://proxy.golang.org

permissions:
    contents: write
    packages: read
    statuses: write
    pull-requests: write

jobs:             
    verify_backend_quality:
      name: Verify Backend Code Quality
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v4
          with:
            version: v1.56.2
            working-directory: ./
            only-new-issues: false
            args: --concurrency=16 --timeout=5m --out-format=github-actions --issues-exit-code=1
            skip-cache: false
            skip-pkg-cache: true

    verify_backend_functionality:
      name: Verify Backend Code Quality
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'

        - name: Verify functionality
          run: go test -v ./tests/...

    publish_release:
      needs: 
        - verify_backend_quality
        - verify_backend_functionality
      runs-on: ubuntu-latest
      steps:
        - name: Set version env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
        - uses: release-drafter/release-drafter@v6
          with:
            disable-autolabeler: true
            name: ${{ env.RELEASE_VERSION }}
            tag: ${{ env.RELEASE_VERSION }}
            version: ${{ env.RELEASE_VERSION }}
            publish: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}